version: '3.8'
services:
    elasticsearch:
        image: elasticsearch:7.4.2
        volumes:
            - journaling-es:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
    kibana:
        image: kibana:7.4.2
        ports:
            - 5601:5601

volumes:
    journaling-es:
