version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    environment:
        # TODO: please no
        - POSTGRES_PASSWORD=password
    volumes:
        - journaling-psql:/var/lib/postgresql/data
volumes:
  journaling-psql: