name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps for CDK
        run: npm ci
        working-directory: ./cdk
      - name: Install deps for server
        run: npm ci
        working-directory: ./journaling-server
      - name: Install deps for client
        run: npm ci
        working-directory: ./journaling-client
      - name: Diff
        run: npm run diff -- JournalingAppStaging
        working-directory: ./cdk
